version: '3.7'
services:
  ml:
    build:
      context: .
      dockerfile: ./ml-flask-api/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - Environment=development
      - FLASK_ENV=development
