version: '3.7'
services:
  ml:
    build:
      context: .
      dockerfile: ./ml-flask-api/Dockerfile
    volumes:
      - './ml-flask-api:/app'
    ports:
      - '5000:5000'
    environment:
      - Environment=development
      - FLASK_ENV=development
